"""Domain definitions independent from battle execution and adapters."""

from towr.domain.actions import AttackAction, InlineRollSource, StatRollSource
from towr.domain.attack_models import (
    AttackRequest,
    ConditionAfterGiveGroundSpec,
    ConditionOnHitSpec,
    ConditionOnGiveGroundOrWoundSpec,
    ConditionImpactSpec,
    DamageImpactSpec,
    DamageProfile,
    HazardImpactSpec,
    NearbyTargetsStaggerSpec,
    ProneBeforeGiveGroundSpec,
    ResilienceProfile,
    SecondaryEffectSpec,
)
from towr.domain.combatants import CombatantDefinition, CombatantState, Side
from towr.domain.condition_models import Condition, ConditionState
from towr.domain.encounters import EncounterDefinition
from towr.domain.injury_models import CharacterInjuryState, ProfileInjuryState
from towr.domain.resolution_models import (
    ConditionAfterGiveGroundRequest,
    ConditionAfterGiveGroundResult,
    GiveGroundDestinationPreference,
    HazardExposureRequest,
    HazardResolutionRequest,
    HazardResolutionResult,
    IdentifiedStaggerTarget,
    KernelAttackRequest,
    MonstrosityReactionOutcome,
    MonstrosityReactionRequest,
    MonstrosityReactionResolutionRequest,
    MonstrosityReactionResolutionResult,
    MonstrosityReactionSpec,
    MonstrousFlightReactionSpec,
    NearbyTargetStaggerResult,
    NearbyTargetsStaggerRequest,
    NearbyTargetsStaggerResolutionRequest,
    NearbyTargetsStaggerResolutionResult,
    ResolutionResult,
    StaggerImpactRequest,
    StaggerImpactResult,
)
from towr.domain.results import BattleOutcome, BattleResult
from towr.domain.stats import DicePool, StatBlock
from towr.domain.test_models import InlineProfile, Skill, TestProfile, TestRequest

__all__ = [
    "AttackAction",
    "AttackRequest",
    "BattleOutcome",
    "BattleResult",
    "CombatantDefinition",
    "CombatantState",
    "CharacterInjuryState",
    "Condition",
    "ConditionAfterGiveGroundRequest",
    "ConditionAfterGiveGroundResult",
    "ConditionAfterGiveGroundSpec",
    "ConditionOnHitSpec",
    "ConditionOnGiveGroundOrWoundSpec",
    "ConditionImpactSpec",
    "ConditionState",
    "DamageImpactSpec",
    "DamageProfile",
    "DicePool",
    "EncounterDefinition",
    "GiveGroundDestinationPreference",
    "InlineRollSource",
    "InlineProfile",
    "HazardImpactSpec",
    "HazardExposureRequest",
    "HazardResolutionRequest",
    "HazardResolutionResult",
    "IdentifiedStaggerTarget",
    "KernelAttackRequest",
    "MonstrosityReactionOutcome",
    "MonstrosityReactionRequest",
    "MonstrosityReactionResolutionRequest",
    "MonstrosityReactionResolutionResult",
    "MonstrosityReactionSpec",
    "MonstrousFlightReactionSpec",
    "NearbyTargetStaggerResult",
    "NearbyTargetsStaggerRequest",
    "NearbyTargetsStaggerResolutionRequest",
    "NearbyTargetsStaggerResolutionResult",
    "NearbyTargetsStaggerSpec",
    "ProfileInjuryState",
    "ProneBeforeGiveGroundSpec",
    "ResilienceProfile",
    "ResolutionResult",
    "SecondaryEffectSpec",
    "Side",
    "Skill",
    "StaggerImpactRequest",
    "StaggerImpactResult",
    "StatBlock",
    "StatRollSource",
    "TestProfile",
    "TestRequest",
]
